# Generated by Django 5.0.1 on 2024-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=15)),
                ('line2', models.CharField(max_length=20)),
                ('line3', models.CharField(max_length=30)),
                ('line4', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('github', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
    ]
