# Generated by Django 5.0.1 on 2024-01-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='certificates')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificate_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('category1', models.CharField(max_length=30)),
                ('category2', models.CharField(max_length=30)),
                ('category3', models.CharField(max_length=30)),
                ('category4', models.CharField(max_length=30)),
            ],
        ),
    ]
