# Generated by Django 5.0.1 on 2024-01-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_persent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='persent',
            field=models.IntegerField(),
        ),
    ]
