# Generated by Django 5.0.1 on 2024-01-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_persent'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='right',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
