# Generated by Django 5.0.1 on 2024-01-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='line4',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='line5',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
