# Generated by Django 5.0.1 on 2024-01-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_aboutme_line4_aboutme_line5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='line2',
            field=models.CharField(max_length=60),
        ),
    ]
